# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 17:32
from __future__ import unicode_literals

import django_countries.fields

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitecode', models.CharField(max_length=254, unique=True)),
                ('sitename', models.CharField(max_length=254)),
                ('release_date', models.CharField(max_length=254)),
                ('country_code', models.CharField(max_length=2)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('sitetype', models.CharField(choices=[('A', 'Special Protection Areas (SPA)'), ('B', 'Special Conservation Interest (SCI)'), ('C', 'Both SPA and SCI')], max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3035)),
            ],
        ),
    ]
