# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 09:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0002_site_centroid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
