# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 18:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0003_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='natura.Site')),
            ],
        ),
    ]
