# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-30 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natura', '0004_auto_20160330_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitats',
            old_name='percentage_cover',
            new_name='percentagecover',
        ),
    ]
