# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 11:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('raster', '0031_auto_20160218_0832'),
        ('corine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorineLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('change', models.BooleanField(default=False)),
                ('rasterlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster.RasterLayer')),
            ],
        ),
    ]
