# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-31 16:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corine', '0002_corinelayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
