# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-04-07 09:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corine', '0004_auto_20160406_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='geom_wgs',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
