# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-04-07 18:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corine', '0005_patch_geom_wgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='geom_wgs',
        ),
        migrations.AddField(
            model_name='patch',
            name='geom_cleaned',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3035),
        ),
    ]
