# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-04-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_centroid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='beginlifes',
        ),
        migrations.RemoveField(
            model_name='region',
            name='f_code',
        ),
        migrations.RemoveField(
            model_name='region',
            name='fcsubtype',
        ),
        migrations.RemoveField(
            model_name='region',
            name='icc',
        ),
        migrations.RemoveField(
            model_name='region',
            name='inspireid',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name0',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='region',
            name='shape_area',
        ),
        migrations.RemoveField(
            model_name='region',
            name='shape_leng',
        ),
        migrations.RemoveField(
            model_name='region',
            name='shn0',
        ),
        migrations.RemoveField(
            model_name='region',
            name='shn1',
        ),
        migrations.RemoveField(
            model_name='region',
            name='shn2',
        ),
        migrations.RemoveField(
            model_name='region',
            name='shn3',
        ),
        migrations.RemoveField(
            model_name='region',
            name='shn4',
        ),
        migrations.RemoveField(
            model_name='region',
            name='taa',
        ),
        migrations.AddField(
            model_name='region',
            name='n0cd',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n0nm',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n0nme',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n1cd',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n1nm',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n2_3cd',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n2cd',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n2nm',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n3cd',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='n3nm',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='nufttp',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='nuts3id',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='level',
            field=models.IntegerField(default=3),
        ),
    ]
