REGION_FIELD_MAPPING = {
    'fcsubtype': 'FCsubtype',
    'inspireid': 'inspireId',
    'beginlifes': 'beginLifes',
    'f_code': 'F_CODE',
    'icc': 'ICC',
    'shn0': 'SHN0',
    'shn1': 'SHN1',
    'shn2': 'SHN2',
    'shn3': 'SHN3',
    'shn4': 'SHN4',
    'taa': 'TAA',
    'shape_leng': 'Shape_Leng',
    'shape_area': 'Shape_Area',
    'geom': 'POLYGON',
}
