# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 10:16
from __future__ import unicode_literals

import django_countries.fields

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuts3id', models.FloatField()),
                ('nufttp', models.CharField(max_length=1)),
                ('n0cd', models.CharField(max_length=2)),
                ('n1cd', models.CharField(max_length=3)),
                ('n2cd', models.CharField(max_length=4)),
                ('n3cd', models.CharField(max_length=5)),
                ('n0nme', models.CharField(max_length=254)),
                ('n0nm', models.CharField(max_length=254)),
                ('n1nm', models.CharField(max_length=254)),
                ('n2nm', models.CharField(max_length=254)),
                ('n3nm', models.CharField(max_length=254)),
                ('n2_3cd', models.CharField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
        ),
    ]
