# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 11:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcsubtype', models.IntegerField(null=True)),
                ('inspireid', models.CharField(max_length=50, null=True)),
                ('beginlifes', models.DateField(null=True)),
                ('f_code', models.CharField(max_length=5, null=True)),
                ('icc', models.CharField(max_length=8, null=True)),
                ('shn0', models.CharField(max_length=14, null=True)),
                ('shn1', models.CharField(max_length=14, null=True)),
                ('shn2', models.CharField(max_length=14, null=True)),
                ('shn3', models.CharField(max_length=14, null=True)),
                ('shn4', models.CharField(max_length=14, null=True)),
                ('taa', models.IntegerField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('level', models.IntegerField(default=3)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
